name: Build and Push (Redactor)
on:
    workflow_dispatch:
        inputs:
            image-tag:
                description: 'Image tag'
                required: true
                default: 'latest'
                type: string
    # push:
    #     branches:
    #         - master
    #     paths:
    #         - "src/redactor/**"
jobs:
    build-push:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout code
                uses: actions/checkout@v4
            -   
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
                name: Build and Push
                uses: docker/build-push-action@v6
                with:
                    context: ./src/redactor
                    tags: ${{ secrets.DOCKERHUB_USERNAME }}/sensihidepdf-redactor:${{ github.event.inputs.image-tag || 'latest' }}
                    push: true
